Spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.16.167.2:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alicloud:
      access-key: LTAI4GJxb8pn8Mjwhc9Fhp7p
      secret-key: dNdCGje904WFh6YYH36LZanVTm0KGt
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 172.16.167.2
    port: 6379


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug


gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10