spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GJxb8pn8Mjwhc9Fhp7p
      secret-key: dNdCGje904WFh6YYH36LZanVTm0KGt
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-tangyao
  application:
    name: gulimall-third-party

server:
  port: 30000
