spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t7tRgdRHUCuyeUVrsPU
      secret-key: VlsJOImh2yWaX9uQ5yfuyLAr5LIugR
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-tangyao
      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appcode: 39e87b2ad4004ae6833750af6851c10a

  application:
    name: gulimall-third-party

server:
  port: 30000
